apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-hpa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-hpa-nginx
  template:
    metadata:
      labels:
        app: sandbox-hpa-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
