apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-deployment-revision-history-limit
  labels:
    app: nginx
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19-alpine
        ports:
        - containerPort: 80
