apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-pod-only
  namespace: kakakakakku-ns
roleRef:
  kind: Role
  name: role-pod-only
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: kakakakakku-user
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: kakakakakku-group
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: kakakakakku-sa
    namespace: kakakakakku-ns
