apiVersion: v1
kind: Pod
metadata:
  name: sandbox-configmap-binary-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.18
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: config-volume
    configMap:
      name: sandbox-configmap-binary
