apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-drain-timeout-nginx
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19-alpine
        resources:
          requests:
            memory: 300Mi
        ports:
        - containerPort: 80
